version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/a9v8q2x1
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t mydemohere .
      - docker tag mydemohere:latest public.ecr.aws/a9v8q2x1/mydemohere:latest
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/a9v8q2x1/mydemohere:latest
      - printf '[{"name":"test","imageUri":"public.ecr.aws/a9v8q2x1/mydemohere:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
